### ISSUE TITLE
Join tablas

### ISSUE THREAD

**Issue by Drusill** [DCC-CC4401/2018-2-DeCepCiones-T4#1]
Para views falta hacer join de las tablas respectivas (landing page en proceso)

**Comment by AlxEnashi** [comment]
Esto ya se soluciono.
Si en un modelo una tabla esta relacionado con "foreinghKey o es manytomany" los datos de la tabla relacionada se pueden acceder como un compo del queryset.
Ej:
coev = Coevaluacion.objects.get(id=1)
coev.curso.nombre (esto da el nombe del curso asociado a la coevaluacion, es 1 a muchos desde el punto de vista de la coevaluacion, por eso nos entrega 1 solo objeto, si fuera muchos a muchos deberiamos filtrar esta nueva "lista").
