### ISSUE TITLE
Pruebas

### ISSUE THREAD

**Issue by AlxEnashi** [DCC-CC4401/2018-2-DeCepCiones-T4#24]
Falta una base de datos mas completas, con mas de 10 coevs para un usuario, todas consistentes, con mas notas y grupos de al menos 3.
Y probar que todo funcione en estas condiciones. 

Nota: dejar guardado el sql de ahora, si todo se rompe, podemos usar el que tenemos y argumentar ignoraicna xD

**Comment by matirojas** [comment]
Listo
